FROM ubuntu:22.04
LABEL mainteiner="marcus.vbrangel@gmail.com"
RUN apt-get update && apt-get install nginx -y && rm -rf /var/lib/apt/lists/*
COPY index.html /var/www/html
WORKDIR /var/www/html
ENV APP_VERSION=1.0.0
EXPOSE 80
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]
