FROM ubuntu:22.04
RUN apt-get update && apt-get install nginx -y && rm -rf /var/lib/apt/lists/*
COPY index.html /var/www/html
WORKDIR /var/www/htmlENV key=value
ENV APP_VERSION=1.0.0
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
